feat: support customize format parsing for config file
kitex-contrib/config-file pull request #3
Opened 2024-01-14 17:29 UTC by Ricky-chen1

feat: support customize format parsing for config file

2024-01-14 17:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kitex-contrib/config-file?pullRequest=3) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kitex-contrib/config-file?pullRequest=3) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kitex-contrib/config-file?pullRequest=3) it.</sub>

2024-01-15 01:02 UTC, li-jin-gou commented
需要签一下 cla 并修复 ci 。

2024-01-15 02:19 UTC, ozline commented on monitor/monitor.go
Monitor 在正常使用中不会涉及，它是由`NewSuite()`来创建的，应该同时修改`NewSuite()`函数

2024-01-15 02:22 UTC, ozline requested changes
test 可以加一个 `SetParser()` 后的解析测试

2024-01-21 07:13 UTC, li-jin-gou commented
license 的日期需要改为 2024 @Ricky-chen1

2024-01-21 14:07 UTC, li-jin-gou requested changes
代码无问题了，需要同步修改一下 readme 和文档

2024-01-21 15:35 UTC, ozline approved these changes
收工！记得改改文档！！

2024-01-21 23:59 UTC, li-jin-gou approved these changes

2024-01-22 00:00 UTC, merged